name: Docker

on:
  workflow_call:

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Docker Build
      uses: docker/setup-buildx-action@v3.3.0

    - name: Download the Build Artifact
      uses: actions/download-artifact@v4.1.6
      with:
        name: programa

    - name: Docker Login
      uses: docker/login-action@v3.1.0
      with:
        username: saacjr
        password: ${{ secrets.PASSWORD_DOCKER_HUB }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5.3.0
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: saacjr/go_ci:${{ github.ref_name }}
